Feature/jfdd14 umd 45 game collision
infoshareacademy/jfdd14-uMnieDziala pull request #34
Opened 2020-03-02 16:57 UTC by SabinaSadowska

2020-03-02 20:58 UTC, zazulec requested changes
WIdzę, że napisałaś ogrom kodu :D Super, że działa.
 Ustawię Request changes bo chce zobaczyć jak to działa ;p
Chciałbym  tylko  żebyś usunęła console.log na clasę mogę przymknąć oko :D

2020-03-02 20:58 UTC, zazulec commented on game.html
> +                <a href="index.html"><button class="onGame-modal__btn onGame-modal__btn--toLandingPage" type="button">Nie</button></a>
mam uwagę do class onGame modal.
wg mnie powinno to być camel case do końca
onGameModal__.     a nie onGame-modal__
jak chcesz to zmieniać to bardzo łatwo jest to zrobić. Klikasz na tekst który chcesz żeby był zmieniony i wciskasz F2 wyświetla się input bez opisu z tekstem który ma być zmieniony.  Wpisujesz nowy tekst i zmienia się wszędzie gdzie jest ten tekst.

2020-03-02 20:58 UTC, zazulec commented on scripts/game.js
> +const scoreOnGame = document.querySelector('.onGame-modal__score');
class on game

2020-03-02 20:58 UTC, zazulec commented on scripts/game.js
> +            console.log("kolizja");
console.log do usunięcia

2020-03-03 09:08 UTC, JuliaLojek commented on scripts/game.js
> +    else if (localStorage.getItem('score') > enemies.length) {
else if powinno być na tym samym poziomie co zamykająca klamra wcześniejszego if

2020-03-03 09:11 UTC, JuliaLojek approved these changes
świetnie! :)

2020-03-03 11:52 UTC, pasrobert approved these changes
Julia i Paweł już wyłapali chyba większość ja bym usunął jeszcze jakieś niepotrzebne entery :)

2020-03-03 14:14 UTC, zazulec approved these changes

2020-03-03 14:14 UTC, merged